; Win API include file

; =============== kernel32 ===============

; Standard handle types:
STD_INPUT_HANDLE  equ 0xfffffff6  ; (unsigned '-10') Handle of the standard input  (e.g., console input)
STD_OUTPUT_HANDLE equ 0xfffffff5  ; (unsigned '-11') Handle of the standard output (e.g., console output)
STD_ERROR_HANDLE  equ 0xfffffff4  ; (unsigned '-12') Handle of the standard error  (e.g., console output)
